import type { ConstructionProject } from '../types/construction';

export const SAMPLE_PROJECTS: ConstructionProject[] = [
  {
    id: 'project-1',
    name: '세종시 스마트 도시 기반시설 구축',
    type: '토목공사',
    scale: '연면적 125,000m² / 도로연장 8.5km',
    budget: '₩ 850억',
    features: [
      'IoT 센서 기반 인프라 모니터링',
      '친환경 우수 저류 시스템',
      '지하 공동구 통합 관리',
      '스마트 신호 시스템 연동',
    ],
    technicalRequirements: [
      'BIM 설계 필수 적용',
      '내진 설계 1등급',
      '스마트 센서 매설 규격 준수',
      '지하매설물 3D 스캐닝',
      '실시간 시공 모니터링 시스템',
    ],
    location: '세종특별자치시 행정중심복합도시',
    period: '2025.03 ~ 2028.06',
    status: '진행중',
    description: '세종시 스마트 도시 조성을 위한 핵심 기반시설 구축 사업으로, IoT 및 디지털 트윈 기술을 활용한 차세대 도시 인프라를 구축합니다.',
  },
  {
    id: 'project-2',
    name: '판교 테크노밸리 제2단지 업무시설',
    type: '건축공사',
    scale: '지상 25층 / 지하 5층 / 연면적 89,000m²',
    budget: '₩ 1,200억',
    features: [
      '제로에너지 건축물 1등급 인증',
      '태양광·지열 하이브리드 에너지',
      '인텔리전트 빌딩 자동화 시스템',
      '모듈러 공법 부분 적용',
    ],
    technicalRequirements: [
      '구조 해석: 비선형 동적 해석',
      '내진 특등급 (진도 VII 이상)',
      'BEMS 에너지 관리 시스템 구축',
      '고강도 콘크리트 80MPa 이상',
      'PC 프리캐스트 부재 30% 이상',
    ],
    location: '경기도 성남시 분당구 판교',
    period: '2025.06 ~ 2028.12',
    status: '설계완료',
    description: '판교 테크노밸리 내 IT 기업 입주를 위한 친환경 고성능 업무시설 신축 프로젝트입니다.',
  },
  {
    id: 'project-3',
    name: '부산항 신항 배후물류단지 조성',
    type: '항만공사',
    scale: '부지면적 320,000m² / 안벽 연장 1.2km',
    budget: '₩ 2,500억',
    features: [
      '자동화 컨테이너 터미널',
      '냉동·냉장 특수 물류 시설',
      'AI 기반 물류 최적화 시스템',
      '친환경 선박 LNG 벙커링 시설',
    ],
    technicalRequirements: [
      '케이슨 공법 기반 안벽 시공',
      '연약지반 처리 (PBD, SCP 공법)',
      '내진 I등급 항만 구조물',
      '자동화 크레인 레일 정밀 시공',
      '해수 침식 방지 특수 코팅',
    ],
    location: '부산광역시 강서구 신항만',
    period: '2024.09 ~ 2029.03',
    status: '시공중',
    description: '부산 신항 배후물류단지 확장 사업으로, 스마트 항만 물류 시스템과 자동화 설비를 포함합니다.',
  },
  {
    id: 'project-4',
    name: '대전 도시철도 2호선 3공구',
    type: '철도/교통공사',
    scale: '노선 연장 4.8km / 정거장 3개소',
    budget: '₩ 3,800억',
    features: [
      '트램 방식 경량전철',
      '지하구간 NATM + Shield TBM 병행',
      '역사 내 자연채광 설계',
      '무인 자동운전 시스템 (GoA4)',
    ],
    technicalRequirements: [
      'Shield TBM 직경 6.9m',
      'NATM 터널 내공 단면 확보',
      '궤도 정밀도 ±2mm 이내',
      '전차선 급전 시스템 750V DC',
      '방재 시스템 SIL-4 등급',
    ],
    location: '대전광역시 서구 ~ 유성구',
    period: '2025.01 ~ 2030.06',
    status: '착공준비',
    description: '대전 도시철도 2호선 건설 사업 중 3공구로, 도심 구간 지하터널 및 정거장 신설 공사입니다.',
  },
  {
    id: 'project-5',
    name: '제주 해상풍력 발전단지 해저케이블',
    type: '전기/에너지공사',
    scale: '해저케이블 연장 32km / 용량 200MW',
    budget: '₩ 680억',
    features: [
      '해저 XLPE 고압 케이블 포설',
      '해양 생태계 영향 최소화 공법',
      '실시간 케이블 상태 모니터링',
      '해류 시뮬레이션 기반 경로 최적화',
    ],
    technicalRequirements: [
      '해저 케이블 매설 깊이 1.5m 이상',
      'HVAC 154kV 해저케이블 규격',
      '해저면 ROV 탐사 및 지반조사',
      'DTS 분포 온도 센서 시스템',
      '해상 크레인 바지 1,200톤급',
    ],
    location: '제주특별자치도 제주시 한림읍 앞바다',
    period: '2025.04 ~ 2027.09',
    status: '허가완료',
    description: '제주 해상풍력 발전단지와 육상 변전소를 연결하는 해저케이블 포설 및 접속 공사입니다.',
  },
  {
    id: 'project-6',
    name: '화성시 동탄 공공하수처리시설 현대화',
    type: '환경/플랜트공사',
    scale: '처리용량 일 80,000m³ / 부지 25,000m²',
    budget: '₩ 450억',
    features: [
      'MBR 막분리 공법 도입',
      '소화가스 발전 시스템',
      '악취 밀폐형 처리 시설',
      '방류수 재이용 시스템',
    ],
    technicalRequirements: [
      'MBR 막 플럭스 25 LMH 이상',
      'T-N 배출 기준 10mg/L 이하',
      'SCADA 통합 제어 시스템',
      '내부식성 STS316L 배관',
      '탈취 효율 99% 이상 바이오필터',
    ],
    location: '경기도 화성시 동탄면',
    period: '2025.07 ~ 2028.03',
    status: '실시설계',
    description: '기존 하수처리시설의 노후 설비를 교체하고, MBR 공법을 도입하여 처리 수질을 대폭 개선하는 현대화 사업입니다.',
  },
];
